package view;

/**
 *
 * @author AguidoRin
 */
public class FrmAtencion extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmIntClínica
     */
    public FrmAtencion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDniPatient = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbxEspec = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        btnAddPatient1 = new javax.swing.JButton();
        btnAddPatient4 = new javax.swing.JButton();
        txtSearchDoctor = new javax.swing.JTextField();
        btnAddPatient3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnAddPatient5 = new javax.swing.JButton();
        txtSearchDoctor1 = new javax.swing.JTextField();
        btnAddPatient6 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atención");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sección", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 310, 42));

        txtDniPatient.setBackground(new java.awt.Color(204, 255, 255));
        txtDniPatient.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtDniPatient.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dni Paciente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        jPanel1.add(txtDniPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 230, 40));

        jDateChooser1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 230, 50));

        jLabel3.setText("Fecha de nacimiento: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        jLabel4.setText("Dni:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 20));

        jLabel6.setText("Teléfono:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabel7.setText("Edad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 20));

        jLabel8.setText("Dirección:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        jLabel9.setText("Género: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("INFORMACIÓN DEL PACIENTE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        cbxEspec.setBackground(new java.awt.Color(204, 255, 255));
        cbxEspec.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cbxEspec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especialidad 1", "Especialidad 2" }));
        cbxEspec.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especialidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        jPanel1.add(cbxEspec, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 238, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Observaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, 110));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Diagnóstico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, 110));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tratamiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 240, 110));

        btnAddPatient1.setBackground(new java.awt.Color(0, 153, 153));
        btnAddPatient1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddPatient1.setText("MODIFICAR");
        jPanel1.add(btnAddPatient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 150, 30));

        btnAddPatient4.setBackground(new java.awt.Color(0, 153, 153));
        btnAddPatient4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddPatient4.setText("LIMPIAR");
        jPanel1.add(btnAddPatient4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 150, 30));

        txtSearchDoctor.setBackground(new java.awt.Color(204, 255, 255));
        txtSearchDoctor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearchDoctor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código atención", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        txtSearchDoctor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSearchDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDoctorActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearchDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 150, 40));

        btnAddPatient3.setBackground(new java.awt.Color(0, 153, 153));
        btnAddPatient3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddPatient3.setText("BUSCAR");
        jPanel1.add(btnAddPatient3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 170, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código atención", "Dni Paciente", "Fecha", "Especialidad", "Medico", "Descripcion Atencion"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 1020, 300));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("REGISTRO ATENCIÓN");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 20));

        btnAddPatient5.setBackground(new java.awt.Color(0, 153, 153));
        btnAddPatient5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddPatient5.setText("AGREGAR");
        jPanel1.add(btnAddPatient5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 150, 30));

        txtSearchDoctor1.setBackground(new java.awt.Color(204, 255, 255));
        txtSearchDoctor1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtSearchDoctor1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código médico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        txtSearchDoctor1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSearchDoctor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchDoctor1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearchDoctor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 180, 40));

        btnAddPatient6.setBackground(new java.awt.Color(0, 153, 153));
        btnAddPatient6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddPatient6.setText("BUSCAR");
        jPanel1.add(btnAddPatient6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1070, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchDoctorActionPerformed

    private void txtSearchDoctor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchDoctor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchDoctor1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddPatient1;
    public javax.swing.JButton btnAddPatient3;
    public javax.swing.JButton btnAddPatient4;
    public javax.swing.JButton btnAddPatient5;
    public javax.swing.JButton btnAddPatient6;
    public javax.swing.JComboBox<String> cbxEspec;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    public javax.swing.JTextField txtDniPatient;
    public javax.swing.JTextField txtSearchDoctor;
    public javax.swing.JTextField txtSearchDoctor1;
    // End of variables declaration//GEN-END:variables
}
