package view;

/**
 *
 * @author AguidoRin
 */
public class FrmAddAttent extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmIntClínica
     */
    public FrmAddAttent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodeDoctor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCodeAtention = new javax.swing.JTextField();
        txtDniPatient = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        cbxAtention = new javax.swing.JComboBox<>();
        cbxEspec = new javax.swing.JComboBox<>();
        txtAttentDetails = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosMedicos = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        txtCodeDoctor.setBackground(new java.awt.Color(204, 255, 255));
        txtCodeDoctor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtCodeDoctor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código de Médico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        txtCodeDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeDoctorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Atención");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sección", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 12))); // NOI18N

        txtCodeAtention.setBackground(new java.awt.Color(204, 255, 255));
        txtCodeAtention.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtCodeAtention.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código de Atención", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        txtCodeAtention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeAtentionActionPerformed(evt);
            }
        });

        txtDniPatient.setBackground(new java.awt.Color(204, 255, 255));
        txtDniPatient.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtDniPatient.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dni Paciente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAdd.setText("AGREGAR ATENCIÓN");

        cbxAtention.setBackground(new java.awt.Color(204, 255, 255));
        cbxAtention.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cbxAtention.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atención 1", "Atención 2", "Atención 3", "Atención 4" }));
        cbxAtention.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atención Brindada", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        cbxEspec.setBackground(new java.awt.Color(204, 255, 255));
        cbxEspec.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cbxEspec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especialidad 1", "Especialidad 2" }));
        cbxEspec.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especialidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        txtAttentDetails.setBackground(new java.awt.Color(204, 255, 255));
        txtAttentDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detalles", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAttentDetails)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxAtention, javax.swing.GroupLayout.Alignment.LEADING, 0, 238, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodeDoctor)
                    .addComponent(txtCodeAtention)
                    .addComponent(txtDniPatient)
                    .addComponent(cbxEspec, javax.swing.GroupLayout.Alignment.LEADING, 0, 238, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodeDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodeAtention, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDniPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxAtention, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxEspec, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAttentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 470));

        tblDatosMedicos.setBackground(new java.awt.Color(204, 255, 255));
        tblDatosMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código De Médico", "Código De Atención", "DNI de paciente", "Atención Brindada", "Tipo de Especialidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatosMedicos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tblDatosMedicos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 640, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeAtentionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeAtentionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeAtentionActionPerformed

    private void txtCodeDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JComboBox<String> cbxAtention;
    public javax.swing.JComboBox<String> cbxEspec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatosMedicos;
    public javax.swing.JTextField txtAttentDetails;
    public javax.swing.JTextField txtCodeAtention;
    public javax.swing.JTextField txtCodeDoctor;
    public javax.swing.JTextField txtDniPatient;
    // End of variables declaration//GEN-END:variables
}
