package view;

/**
 *
 * @author AguidoRin
 */
public class FrmAgregarDoctor extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmIntClínica
     */
    public FrmAgregarDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cbxEspec = new javax.swing.JComboBox<>();
        txtTelefono1 = new javax.swing.JTextField();
        btnAddPatient2 = new javax.swing.JButton();
        btnAddPatient1 = new javax.swing.JButton();
        btnAddPatient3 = new javax.swing.JButton();
        btnAddPatient4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAddPatient = new javax.swing.JButton();
        txtDni1 = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCode.setBackground(new java.awt.Color(204, 255, 255));
        txtCode.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtCode.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        jPanel1.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 238, 40));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medicos");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sección", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 12))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 238, 42));

        txtName.setBackground(new java.awt.Color(204, 255, 255));
        txtName.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombres", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 238, -1));

        txtDni.setBackground(new java.awt.Color(204, 255, 255));
        txtDni.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtDni.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dni", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 238, 40));

        txtTelefono.setBackground(new java.awt.Color(204, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 238, 40));

        cbxEspec.setBackground(new java.awt.Color(204, 255, 255));
        cbxEspec.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cbxEspec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiología", "Pediatría", "Ginecología", "Dermatología", "Traumatología", "Neurología", "Oftalmología", "Psiquiatría", "Endocrinología", "Gastroenterología" }));
        cbxEspec.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especialidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 1, 12))); // NOI18N
        jPanel1.add(cbxEspec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 238, 40));

        txtTelefono1.setBackground(new java.awt.Color(204, 255, 255));
        txtTelefono1.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        txtTelefono1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Book Antiqua", 1, 12))); // NOI18N
        jPanel1.add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 240, -1));

        btnAddPatient2.setBackground(new java.awt.Color(0, 153, 153));
        btnAddPatient2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddPatient2.setText("AGREGAR");
        jPanel1.add(btnAddPatient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 150, 30));

        btnAddPatient1.setBackground(new java.awt.Color(0, 153, 153));
        btnAddPatient1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddPatient1.setText("MODIFICAR");
        jPanel1.add(btnAddPatient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 150, 30));

        btnAddPatient3.setBackground(new java.awt.Color(0, 153, 153));
        btnAddPatient3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddPatient3.setText("ELIMINAR");
        jPanel1.add(btnAddPatient3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 150, 30));

        btnAddPatient4.setBackground(new java.awt.Color(0, 153, 153));
        btnAddPatient4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddPatient4.setText("LIMPIAR");
        jPanel1.add(btnAddPatient4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 150, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 830, 500));

        btnAddPatient.setBackground(new java.awt.Color(0, 153, 153));
        btnAddPatient.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAddPatient.setText("BUSCAR");
        jPanel1.add(btnAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 170, 30));

        txtDni1.setBackground(new java.awt.Color(204, 255, 255));
        txtDni1.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        txtDni1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dni buscado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Book Antiqua", 1, 12))); // NOI18N
        jPanel1.add(txtDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddPatient;
    public javax.swing.JButton btnAddPatient1;
    public javax.swing.JButton btnAddPatient2;
    public javax.swing.JButton btnAddPatient3;
    public javax.swing.JButton btnAddPatient4;
    public javax.swing.JComboBox<String> cbxEspec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField txtCode;
    public javax.swing.JTextField txtDni;
    public javax.swing.JTextField txtDni1;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
