package view;

/**
 *
 * @author AguidoRin
 */
public class FrmClinica extends javax.swing.JFrame {

    /**
     * Creates new form FrmClínica
     */
    public FrmClinica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDpFondo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmPacientes = new javax.swing.JMenu();
        jMenuItem_Pacientes = new javax.swing.JMenuItem();
        jMenuItem_BuscarPaciente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_Doctores = new javax.swing.JMenuItem();
        jMenuItem_AtencionesMedico = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_Especialidad = new javax.swing.JMenuItem();
        jMenuItem_BuscarEspecialidad = new javax.swing.JMenuItem();
        jMenuItem_Atenciones = new javax.swing.JMenu();
        jMenuItem_Atencion = new javax.swing.JMenuItem();
        jMenuItem_BuscarAtenciones = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_HistoriaClinica = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem_Reportes = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem_salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 700));

        jmPacientes.setForeground(new java.awt.Color(0, 0, 0));
        jmPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/paciente.png"))); // NOI18N
        jmPacientes.setText("Pacientes");
        jmPacientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jmPacientes.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_Pacientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_Pacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gestion-pacientes.png"))); // NOI18N
        jMenuItem_Pacientes.setText("Gestionar Pacientes");
        jMenuItem_Pacientes.setPreferredSize(new java.awt.Dimension(180, 30));
        jmPacientes.add(jMenuItem_Pacientes);

        jMenuItem_BuscarPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_BuscarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gestion-pacientes.png"))); // NOI18N
        jMenuItem_BuscarPaciente.setText("Buscar Pacientes");
        jMenuItem_BuscarPaciente.setPreferredSize(new java.awt.Dimension(180, 30));
        jmPacientes.add(jMenuItem_BuscarPaciente);

        jMenuBar1.add(jmPacientes);

        jMenu2.setForeground(new java.awt.Color(0, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/doctor.png"))); // NOI18N
        jMenu2.setText("Doctores");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_Doctores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_Doctores.setText("Gestionar Doctores");
        jMenuItem_Doctores.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu2.add(jMenuItem_Doctores);

        jMenuItem_AtencionesMedico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_AtencionesMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gestion-pacientes.png"))); // NOI18N
        jMenuItem_AtencionesMedico.setText("Atenciones de Medico");
        jMenuItem_AtencionesMedico.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu2.add(jMenuItem_AtencionesMedico);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(0, 0, 0));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/especialidades.png"))); // NOI18N
        jMenu3.setText("Especialidades");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_Especialidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_Especialidad.setText("Gestionar Especialidades");
        jMenuItem_Especialidad.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu3.add(jMenuItem_Especialidad);

        jMenuItem_BuscarEspecialidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_BuscarEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gestion-pacientes.png"))); // NOI18N
        jMenuItem_BuscarEspecialidad.setText("Buscar Especialidades");
        jMenuItem_BuscarEspecialidad.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu3.add(jMenuItem_BuscarEspecialidad);

        jMenuBar1.add(jMenu3);

        jMenuItem_Atenciones.setForeground(new java.awt.Color(0, 0, 0));
        jMenuItem_Atenciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/atencion-medica.png"))); // NOI18N
        jMenuItem_Atenciones.setText("Atenciones");
        jMenuItem_Atenciones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenuItem_Atenciones.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_Atencion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_Atencion.setText("Gestionar Atenciones");
        jMenuItem_Atencion.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_Atenciones.add(jMenuItem_Atencion);

        jMenuItem_BuscarAtenciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_BuscarAtenciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gestion-pacientes.png"))); // NOI18N
        jMenuItem_BuscarAtenciones.setText("Buscar Atenciones");
        jMenuItem_BuscarAtenciones.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenuItem_Atenciones.add(jMenuItem_BuscarAtenciones);

        jMenuBar1.add(jMenuItem_Atenciones);

        jMenu6.setForeground(new java.awt.Color(0, 0, 0));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/historia-clinica.png"))); // NOI18N
        jMenu6.setText("HistoriaClinica");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_HistoriaClinica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_HistoriaClinica.setText("Gestionar Historia Clinica");
        jMenuItem_HistoriaClinica.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu6.add(jMenuItem_HistoriaClinica);

        jMenuBar1.add(jMenu6);

        jMenu7.setForeground(new java.awt.Color(0, 0, 0));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reportes.png"))); // NOI18N
        jMenu7.setText("Reportes");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_Reportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_Reportes.setText("Gestionar Reportes");
        jMenuItem_Reportes.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu7.add(jMenuItem_Reportes);

        jMenuBar1.add(jMenu7);

        jMenu9.setBackground(java.awt.SystemColor.control);
        jMenu9.setForeground(new java.awt.Color(0, 0, 0));
        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salida.png"))); // NOI18N
        jMenu9.setText("Salir");
        jMenu9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu9.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem_salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem_salir.setText("Cerrar Sesion");
        jMenuItem_salir.setPreferredSize(new java.awt.Dimension(180, 30));
        jMenu9.add(jMenuItem_salir);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDpFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClinica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jDpFondo;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem_Atencion;
    private javax.swing.JMenu jMenuItem_Atenciones;
    public javax.swing.JMenuItem jMenuItem_AtencionesMedico;
    public javax.swing.JMenuItem jMenuItem_BuscarAtenciones;
    public javax.swing.JMenuItem jMenuItem_BuscarEspecialidad;
    public javax.swing.JMenuItem jMenuItem_BuscarPaciente;
    public javax.swing.JMenuItem jMenuItem_Doctores;
    public javax.swing.JMenuItem jMenuItem_Especialidad;
    public javax.swing.JMenuItem jMenuItem_HistoriaClinica;
    public javax.swing.JMenuItem jMenuItem_Pacientes;
    public javax.swing.JMenuItem jMenuItem_Reportes;
    public javax.swing.JMenuItem jMenuItem_salir;
    private javax.swing.JMenu jmPacientes;
    // End of variables declaration//GEN-END:variables
}